title: "Documentation Templater"

params:
  # Enable local search
  offlineSearch: true
  ui:
    # disables search bar on the left navigation
    sidebar_search_disable: true
    sidebar_menu_foldable: true
    showLightDarkModeMenu: true  

# Create a new output format
outputFormats:
  viewer:
    baseName: viewer
    isPlainText: false
    mediaType: text/html
    path: bpmn
    permalinkable: true

# Specify the page kinds for which to render this output format
outputs:
  home:
    - HTML
    - Viewer   

module:
  hugoVersion:
    min: 0.73.0

  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
