title: "Documentation Templater"

params:
  # Enable local search
  offlineSearch: true
  custom_js: 
    - js/custom.js
  ui:
    # disables search bar on the left navigation
    sidebar_search_disable: true
    sidebar_menu_foldable: true
    showLightDarkModeMenu: true  

markup:
  goldmark:
    renderer:
      # Needed for HTML tables in markdown
      unsafe: true

# Create a new output format
outputFormats:
  viewer:
    baseName: viewer
    isPlainText: false
    mediaType: text/html
    path: bpmn

# Specify the page kinds for which to render this output format
outputs:
  home:
    - HTML
    - Viewer   

module:
  hugoVersion:
    min: 0.128.0

  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
