name: PR Preview Deployment ðŸš€

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pull-requests: write

# Limit the concurrency of entire workflow
concurrency: deploy-pr-preview-${{ github.ref }}

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  build-hugo-128:
    runs-on: [ubuntu-latest]
    if: github.event.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f #v3.0.0
        with:
          hugo-version: "0.128.0"
          extended: true

      - name: Install postcss-cli and autoprefixer
        run: "npm install postcss-cli autoprefixer"

      - name: Build
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --contentDir ./internal \
            --destination custom \
            --baseURL https://${REPO_OWNER}.github.io/${REPO_NAME}/pr-preview/pr-${{ env.PR_NUMBER }}/custom/

      - name: Upload custom artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: hugo-custom
          path: custom

  build-hugo-latest:
    runs-on: [ubuntu-latest]
    if: github.event.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f #v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Install postcss-cli and autoprefixer
        run: "npm install postcss-cli autoprefixer"

      - name: Build
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --contentDir ./internal \
            --destination latest \
            --baseURL https://${REPO_OWNER}.github.io/${REPO_NAME}/pr-preview/pr-${{ env.PR_NUMBER }}/latest/

      - name: Upload latest artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: hugo-latest
          path: latest

  deploy:
    needs: [build-hugo-128, build-hugo-latest]
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.head.repo.full_name == github.repository
    env:
      DEPLOY_PATH: tmp
    steps:
      # needed so the working directory is recognized as a Git repository
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Create a folder with all compiled versions
        if: github.event.action != 'closed'
        run: |
          mkdir -p ${{ env.DEPLOY_PATH }}

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        if: github.event.action != 'closed'
        with:
          name: hugo-custom
          path: ${{ env.DEPLOY_PATH }}/custom

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        if: github.event.action != 'closed'
        with:
          name: hugo-latest
          path: ${{ env.DEPLOY_PATH }}/latest

      - name: Generate index.html for Deployed Apps
        if: github.event.action != 'closed'
        run: |
          echo "<!DOCTYPE html><head><title>PR Preview</title></head><html><body><h1>Deployed Hugo Templater for PR ${GITHUB_HEAD_REF}</h1><ul>" > ${{ env.DEPLOY_PATH }}/index.html        
          echo "<li><a href='./custom/index.html' target="_blank">Hugo ${HUGO_VERSION}</a></li>" >> ${{ env.DEPLOY_PATH }}/index.html
          echo "<li><a href='./latest/index.html' target="_blank">Hugo latest</a></li>" >> ${{ env.DEPLOY_PATH }}/index.html
          echo "</ul></body></html>" >> ${{ env.DEPLOY_PATH }}/index.html

      - uses: rossjrw/pr-preview-action@2fb559e4766555e23d07b73d313fe97c4f8c3cfe #v1.6.1
        with:
          source-dir: ${{ env.DEPLOY_PATH }}/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
